spring:
  application:
    name: batchservice
  config:
    import: optional:file:env/.env[.properties]

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(bzF57UX9J+VNuenmvvRvXXnkIXR/fRQoBQk6lUANP5EXyjjHWALPfLcMU9OWjQE4gYH3BsenQuWp60pDHusTNWxFVy+9Keg4X/UWP1XW1ZoQKSe85KMQzbN2a3oGfphMLlunbUlwrP+GhBAdFMaXJg==)
    username: ENC(c0hvAR8cVurLw3xqQu3+24Ysv+hcYhgSkhAnll+KvVduK0f3S0IYjxMXptMAYa0/)
    password: ENC(z8HenqC21c3wyOQbKxc3mpxZzpGmu201NReq0VaSkbKrGFPV0NYEZcpl7H6mUbbT)

  batch:
    jdbc:
      initialize-schema: always

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

krx:
  apiUrl: https://data-dbg.krx.co.kr/svc/apis/etp/etf_bydd_trd
  apikey: ENC(RJfTdf9ATiEct5Q2T1tT2tRr55DvD3WSR/EnI0xhvVNKq1jkzGPuxULKRjzN3S9wu/TyqHHS8tydXejPRpeGQhwr6ZeV4Pi5NwH3bpaHWZ8=)