name: set_jasypt_secret_key.yml
on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Make Jasypt Secret Key Env
        run: |
          touch ./.env
          echo "${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}" > ./.env
